export const mbtiDossiers = [
  {
    type: "ISTJ",
    name: "血线维修员",
    route: "人格投影 · ISTJ",
    level: "设施异体 · 裂隙级 Ⅱ",
    visualStyle: "档案铅印",
    image: "/assets/expressive-bloodline-maintainer.png",
    story: "它把每一根走失的线缆重新接回编号。它不解释为什么要这样做，只会在清晨前让所有该亮的灯重新亮起。",
    habitat: "末班列车后的 07 号维修区",
    taboo: "不要替它拾起掉落的编号牌。",
  },
  {
    type: "ISFJ",
    name: "雾灯引路员",
    route: "人格投影 · ISFJ",
    level: "路径异体 · 引导级 Ⅰ",
    visualStyle: "铅印雾景",
    image: "/assets/expressive-fog-lamp-guide.png",
    story: "它总会替最后一个离开的人留一盏灯。即使没有人记得来路，雾灯仍然会把脚步带回安全的站台。",
    habitat: "废线尽头的 03 号引导台",
    taboo: "不要从它手里接走还未点亮的灯。",
  },
  {
    type: "INFJ",
    name: "失物保管员",
    route: "人格投影 · INFJ",
    level: "封存异体 · 静默级 Ⅰ",
    visualStyle: "柜台怪诞",
    image: "/assets/catalog-lost-property-clerk.png",
    story: "它为每件失物保留最后一次被想起的温度。所有没能说出口的告别，都会被它安静地放进最上层抽屉。",
    habitat: "废站地下的失物保管室",
    taboo: "不要向它描述你遗失的人；它会递来一把不属于你的钥匙。",
  },
  {
    type: "INTJ",
    name: "潮痕档案员",
    route: "人格投影 · INTJ",
    level: "封存异体 · 潮位级 Ⅱ",
    visualStyle: "潮痕档案",
    image: "/assets/expressive-tide-mark-archivist.png",
    story: "它把每一次涨潮留下的异常归类成册。没有人见过它休息，因为下一页记录总会在它落笔前自行浮出水面。",
    habitat: "潮位以下的旧档案室",
    taboo: "不要替它盖上最后一枚空白印章。",
  },
  {
    type: "ISTP",
    name: "门缝接线员",
    route: "人格投影 · ISTP",
    level: "边界异体 · 楼道级 Ⅲ",
    visualStyle: "维修现场",
    image: "/assets/catalog-door-gap-switcher.png",
    story: "它负责把断掉的门铃、走廊灯和深夜的求救声接回原本的房间。维修结束后，门缝另一侧总会安静一会儿。",
    habitat: "旧公寓没有门牌的楼层",
    taboo: "它维修门缝时不要报出房号。",
  },
  {
    type: "ISFP",
    name: "伞骨缝补匠",
    route: "人格投影 · ISFP",
    level: "雨幕异体 · 雨幕级 Ⅱ",
    visualStyle: "雨夜插画",
    image: "/assets/catalog-umbrella-rib-mender.png",
    story: "它把被风折断的伞骨逐根缝好，再把无处躲雨的人送进伞下。合上的伞面里，总保留着一场不属于此地的雨。",
    habitat: "旧商业街尽头的雨棚摊位",
    taboo: "不要替它撑开正在缝合的黑伞。",
  },
  {
    type: "INFP",
    name: "纸月拾荒者",
    route: "人格投影 · INFP",
    level: "河岸异体 · 月影级 Ⅰ",
    visualStyle: "民俗水墨",
    image: "/assets/mbti-paper-moon-gatherer.png",
    story: "它沿着河岸捡起被风吹碎的纸月，再把碎片折成会发光的小船。每一艘都载着一个无人知晓的愿望。",
    habitat: "涨潮后的旧河市",
    taboo: "不要问它篮子里哪一片月亮最完整。",
  },
  {
    type: "INTP",
    name: "深井拆解员",
    route: "人格投影 · INTP",
    level: "工业异体 · 井底级 Ⅱ",
    visualStyle: "工业怪诞",
    image: "/assets/mbti-deep-well-disassembler.png",
    story: "它拆开从不再响动的仪表，试图找出声音离开世界的那一刻。它的桌上总放着一枚尚未决定用途的螺丝。",
    habitat: "地下泵房第九层",
    taboo: "不要替它旋回已经取下的零件。",
  },
  {
    type: "ESTP",
    name: "蜕壳巡犬",
    route: "人格投影 · ESTP",
    level: "野外异体 · 边界级 Ⅲ",
    visualStyle: "野外纪实",
    image: "/assets/shell-shed-patrol-hound-v2.png",
    story: "它沿着村界巡行，把散落在雨地里的脚印逐枚送回原处。风声变大时，它反而会走得更快。",
    habitat: "旧村庄外的芦苇巡界亭",
    taboo: "不要对着它的脚印数到第七步。",
  },
  {
    type: "ESFP",
    name: "灯眼邮差",
    route: "人格投影 · ESFP",
    level: "投递异体 · 雨巷级 Ⅱ",
    visualStyle: "雨巷铅印",
    image: "/assets/catalog-lantern-eyed-courier.png",
    story: "它只投递从未寄出的信。每到雨最大的时刻，它会站在灯下，把一封本该被遗忘的信送到仍亮着的窗前。",
    habitat: "雨后的旧城投递巷",
    taboo: "不要替它确认收件人。",
  },
  {
    type: "ESTJ",
    name: "站台检票员",
    route: "人格投影 · ESTJ",
    level: "站台异体 · 站台级 Ⅱ",
    visualStyle: "旧纸站台",
    image: "/assets/catalog-platform-ticket-inspector.png",
    story: "末班车停运后，它仍会逐张检验没有目的地的票根。被它打过孔的人，总能在下一次入睡前抵达一段未曾离开的站台。",
    habitat: "雨夜停运的郊区月台",
    taboo: "不要让它看见空白票根的背面。",
  },
  {
    type: "ESFJ",
    name: "倒影收银员",
    route: "人格投影 · ESFJ",
    level: "夜市异体 · 静默级 Ⅱ",
    visualStyle: "柜台怪诞",
    image: "/assets/catalog-reflection-cashier.png",
    story: "它记得每一枚硬币落在托盘上的声音，却始终记不住自己究竟站在柜台哪一边。玻璃里的那一位会替它把找零算完。",
    habitat: "零点以后仍亮着的无名便利店",
    taboo: "结账时不要看向柜台下方。",
  },
  {
    type: "ENFJ",
    name: "晨雾传令官",
    route: "人格投影 · ENFJ",
    level: "雾廊异体 · 引导级 Ⅱ",
    visualStyle: "雾光绘本",
    image: "/assets/mbti-mist-herald.png",
    story: "它会把没人敢打开的信放到仍愿意接住的人手里。雾最浓时，它的灯笼会先替所有人照出下一步。",
    habitat: "晨雾未散的旧疗养院走廊",
    taboo: "不要替它拆开带着红线的信封。",
  },
  {
    type: "ENTJ",
    name: "钟楼监工",
    route: "人格投影 · ENTJ",
    level: "钟楼异体 · 时序级 Ⅲ",
    visualStyle: "哥特机械",
    image: "/assets/mbti-bell-tower-foreman.png",
    story: "它每天夜里把整座城市的失准时间拧回原位。若有一枚齿轮拒绝转动，它会一直站在钟面后直到天亮。",
    habitat: "暴雨中的北塔钟楼",
    taboo: "不要替它报时；你的声音会被编进下一轮钟响。",
  },
  {
    type: "ENTP",
    name: "镜门游商",
    route: "人格投影 · ENTP",
    level: "镜界异体 · 折光级 Ⅱ",
    visualStyle: "异形卡通",
    image: "/assets/mbti-mirror-gate-peddler.png",
    story: "它卖的镜子只照出尚未发生的选择。每当有人问价，它便换一种声音回答，仿佛柜台后还站着更多的自己。",
    habitat: "旧公寓中央的流动镜摊",
    taboo: "不要把两面镜子同时对准它。",
  },
  {
    type: "ENFP",
    name: "萤群旅人",
    route: "人格投影 · ENFP",
    level: "夜路异体 · 微光级 Ⅰ",
    visualStyle: "夜雨电影写实",
    image: "/assets/mbti-firefly-traveler-v2.png",
    story: "它总在雨停后抵达没有班次的站牌。发间的萤火会替它记住每一段偶然同行的路，影子却永远比它多等一班车。",
    habitat: "没有线路图的乡道候车亭",
    taboo: "不要问它下一班车去哪里。",
  },
];

export const mbtiDossierByType = Object.fromEntries(
  mbtiDossiers.map((dossier) => [dossier.type, dossier]),
);
